apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-manager
  namespace: argocd
spec:
  destination:
    namespace: argocd
  project: system
  source:
    repoURL: https://github.com/jesseops/enterprise-grade-k8s-local.git
  syncPolicy:
    automated:
      selfHeal: true
