apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-manager
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: REPLACEME
  project: system
  source:
    path: REPLACEME
    repoURL: git@github.com:jesseops/enterprise-grade-k8s-local.git
  syncPolicy:
    automated:
      selfHeal: true
