apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./base

nameSuffix: -infra

patches:
  - target:
      kind: Application
      name: argo-app-manager
    path: ./overlays/app-manager.yaml
  - target:
      kind: Application
    patch: |-
      - op: replace
        path: /spec/destination/name
        value: infra
    options:
      allowNameChange: true
