apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-manager-infra
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: infra
  source:
    path: argocd/app_manager/infra
