apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-manager
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: infra
  source:
    path: argocd/app_manager/infra
