apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-manager-prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: prod
  source:
    path: argocd/app_manager/prod
