apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-app-manager
spec:
  destination:
    namespace: argocd
    name: prod
  source:
    path: argocd/app_manager/prod
